---
version: "3.8"
services:
  api:
    build:
      context: ./api_service/docker
      dockerfile: docker/api.Dockerfile

  blockchain:
    build:
      context: ./blockchain_service/docker
      dockerfile: docker/blockchain.Dockerfile

  cli:
    build:
      context: ./cli_service/docker
      dockerfile: docker/cli.Dockerfile

  global_config:
    build:
      context: ./global_config_service/docker
      dockerfile: docker/global_config.Dockerfile

  consensus:
    build:
      context: ./consensus_service/docker
      dockerfile: docker/consensus.Dockerfile

  crosschain:
    build:
      context: ./crosschain_service/docker
      dockerfile: docker/crosschain.Dockerfile

  defi:
    build:
      context: ./defi_service/docker
      dockerfile: docker/defi.Dockerfile

  governance:
    build:
      context: ./governance_service/docker
      dockerfile: docker/governance.Dockerfile

  infra:
    build:
      context: ./infra_service/docker
      dockerfile: docker/infra.Dockerfile

  layer2:
    build:
      context: ./layer2_service/docker
      dockerfile: docker/layer2.Dockerfile

  orchestration:
    build:
      context: ./orchestration_service/docker
      dockerfile: docker/orchestration.Dockerfile

  p2p:
    build:
      context: ./p2p_service/docker
      dockerfile: docker/p2p.Dockerfile

  raas:
    build:
      context: ./raas_service/docker
      dockerfile: docker/raas.Dockerfile

  relay:
    build:
      context: ./relay_service/docker
      dockerfile: docker/relay.Dockerfile

  rollups:
    build:
      context: ./rollups_service/docker
      dockerfile: docker/rollups.Dockerfile

  smart_contract:
    build:
      context: ./smart_contract_service/docker
      dockerfile: docker/smart_contract.Dockerfile

  storage:
    build:
      context: ./storage_service/docker
      dockerfile: docker/storage.Dockerfile

  tokens:
    build:
      context: ./tokens_service/docker
      dockerfile: docker/tokens.Dockerfile

  tui:
    build:
      context: ./tui_service/docker
      dockerfile: docker/tui.Dockerfile

  vm:
    build:
      context: ./vm_service/docker
      dockerfile: docker/vm.Dockerfile

  wallet:
    build:
      context: ./wallet_service/docker
      dockerfile: docker/wallet.Dockerfile

  zkp:
    build:
      context: ./zkp_service/docker
      dockerfile: docker/zkp.Dockerfile

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
networks:
  default:
    driver: bridge
